export const typography = {
  title1: "text-normal text-DarkFontColor1 ",
  title2: "text-bold text-DarkFontColor2 ",
  title3: "text-normal text-DarkFontColor2 ",
  title4: "text-bold text-DarkFontColor1 ",
  bannerTitle: "text-bold text-BannerFontColor ",
  bannerSubtitle:"text-bannersub text-BannerFontColor",
  bigvs: "text-extrabold text-DarkFontColor2",
  subtitle1: "text-sub text-DarkFontColor1",
  subtitle2: "text-sub text-DarkFontColor2",
  subtitle3: "",
  subtitle4: "",
  p1: "",
  p2: "",
};
